<?php

/**
 * @file
 * Functions to support theming in the alacazar theme.
 */

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 */
function alcazar_preprocess_html(&$variables) {

}

function alcazar_preprocess_links(&$variables) {
    if (isset($variables['links']['node-readmore'])) {
      $variables['links']['node-readmore']['link']['#title'] = t('download plan');
    }
}